### ISSUE TITLE
Tasks callbacks with inputs fail. 

### ISSUE THREAD

**Issue by dr-mrsthemonarch** [arkhipenko/TaskScheduler#139]
With this minimal Code:

```
#include <array>
#include <Arduino.h>

std::array<std::array<float, 3> , 2> vals = {0}; //imagine this is full of sensor data
String stringRead;
int cs14 = 1;
#define _TASK_SCHEDULING_OPTIONS
#include <TaskScheduler.h>


void cs14Print(int pin );
Scheduler runner;
//Tasks
Task sensor14(1000, TASK_FOREVER, &cs14Print(int pin));

void cs14Print(int pin) {
  Serial.print(vals[pin][0]);
  Serial.print(',');
  Serial.print(vals[pin][1]);
  Serial.print(',');
  Serial.println(vals[pin][2]);
};

void setup() {
  // serial to display data
  Serial.begin(115200);
  //  delay(100);
  runner.init();
  runner.addTask(sensor14);
  sensor14.enable();
}

void loop() {
  runner.execute();
}
```

I'm trying to create tasks that I can feed various values, rather than repeating code over and over again for various tasks. I have developed a CLI that can take different Integers to turn on or off different sensors through using SPI and chip select (some 16 differents sensors) 

Though it seems this isn't possible, as I get the following error, or various different ones when trying to start a task callback with variables.

```
taskwithoptions:15:46: error: expected primary-expression before 'int'
 Task sensor14(1000, TASK_FOREVER, &cs14Print(int pin));
                                              ^~~
exit status 1
expected primary-expression before 'int'
```

 nor can I find in any of your (excellent) examples of this being done either. Is this not possible? Or is there a better way around this? Love using the library otherwise!

**Comment by arkhipenko** [comment]
You cannot pass parameters to the callback methods. You have to use LTS for that - check appropriate examples. Sent from a mobile device. Apologies for autocorrect. On Mar 15, 2022 3:52 PM, DoctorGirlfriend ***@***.***> wrote:
With this minimal Code:
#include <array>
#include <Arduino.h>

std::array<std::array<float, 3> , 2> vals = {0}; //imagine this is full of sensor data
String stringRead;
int cs14 = 1;
#define _TASK_SCHEDULING_OPTIONS
#include <TaskScheduler.h>


void cs14Print(int pin );
Scheduler runner;
//Tasks
Task sensor14(1000, TASK_FOREVER, &cs14Print(int pin));

void cs14Print(int pin) {
  Serial.print(vals[pin][0]);
  Serial.print(',');
  Serial.print(vals[pin][1]);
  Serial.print(',');
  Serial.println(vals[pin][2]);
};

void setup() {
  // serial to display data
  Serial.begin(115200);
  //  delay(100);
  runner.init();
  runner.addTask(sensor14);
  sensor14.enable();
}

void loop() {
  runner.execute();
}

I'm trying to create tasks that I can feed various values, rather than repeating code over and over again for various tasks. I have developed a CLI that can take different Integers to turn on or off different sensors through using SPI and chip select (some 16 differents sensors)
Though it seems this isn't possible, as I get the following error, or various different ones when trying to start a task callback with variables.
taskwithoptions:15:46: error: expected primary-expression before 'int'
 Task sensor14(1000, TASK_FOREVER, &cs14Print(int pin));
                                              ^~~
exit status 1
expected primary-expression before 'int'

nor can I find in any of your (excellent) examples of this being done either. Is this not possible? Or is there a better way around this? Love using the library otherwise!
