### ISSUE TITLE
#include error from c++ compiler due to multiple definition error

### ISSUE THREAD

**Issue by theionSami** [arkhipenko/TaskScheduler#143]
first i want to thank you for the great work.
As the cpp compiler seems not happy only with header files, it complains whenever i include the "taskScheduler.h" in other header than main.cpp
As far i know it need to find the implementation files for your library. otherwise it complains about multiple definitinons ...
Is there any version/ branch where we can find .h and .cpp from yours.
Thank you

**Comment by arkhipenko** [comment]
This is how you do it:

https://github.com/arkhipenko/TaskScheduler/tree/master/examples/Scheduler_example27_PlatformIO
[https://opengraph.githubassets.com/6b9ea2568b35c75afe9cd1a947da50e9dd93fb6b083d59db82f546f27a4511a8/arkhipenko/TaskScheduler]<https://github.com/arkhipenko/TaskScheduler/tree/master/examples/Scheduler_example27_PlatformIO>
TaskScheduler/examples/Scheduler_example27_PlatformIO at master · arkhipenko/TaskScheduler<https://github.com/arkhipenko/TaskScheduler/tree/master/examples/Scheduler_example27_PlatformIO>
Cooperative multitasking for Arduino, ESPx, STM32, nRF and other microcontrollers - TaskScheduler/examples/Scheduler_example27_PlatformIO at master · arkhipenko/TaskScheduler
github.com

________________________________
From: sami-theion ***@***.***>
Sent: Wednesday, May 18, 2022 12:43 PM
To: arkhipenko/TaskScheduler ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [arkhipenko/TaskScheduler] #include error from c++ compiler due to multiple definition error (Issue #143)


first i want to thank you for the great work.
As the cpp compiler seems not happy only with header files, it complains whenever i include the "taskScheduler.h" in other header than main.cpp
As far i know it need to find the implementation files for your library. otherwise it complains about multiple definitinons ...
Is there any version/ branch where we can find .h and .cpp from yours.
Thank you

**Comment by Jozott00** [comment]
For everyone who also has the linking problem with `TaskScheduler.h`:

It is important that only one file with the `#define TaskScheduler.h` macro is compiled! Therefore the PlatformIO example has a `TaskScheduler.cpp` file with just this macro. 

All other files (including `main.cpp`) that have to use the library must use `#define TaskSchedulerDeclarations.h` to get linked without an error!
