### ISSUE TITLE
<avr/wdt.h>

### ISSUE THREAD

**Issue by Fbo06** [arkhipenko/TaskScheduler#18]
Hello, first at all congratulations and thank you for your hard work ! 
i have a problem to compile the 7th example who use #include <avr/wdt.h>
it say : "No such file or directory"
can you tell me, please, how can i do to make it work ?

**Comment by arkhipenko** [comment]
Hi.

I will currently on vacation, but will look into this on Sunday.


Could you please make sure you install the library into appropriate folder with appropriate folder structure?


Also, please let me know which version of Arduino GUI do you use, and which target device do you compile for? (Not all devices support WDT).





Sent from a mobile device. Apologies for accidental typos.






On Fri, Jul 22, 2016 at 4:05 PM +0200, "Fbo06" <notifications@github.com> wrote:





Hello, first at all congratulations and thank you for your hard work !
i have a problem to compile the 7th example who use #include <avr/wdt.h>
it say : "No such file or directory"
can you tell me, please, how can i do to make it work ?

---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/arkhipenko/TaskScheduler/issues/18

**Comment by Fbo06** [comment]
Hi Anatoli,
Thank you to respond me so quickly 
- i install the library by the Arduino GUI
- Arduino GUI is 1.6.8
- The Target Device is : WeMos D1 R2 & Mini
All the Samples work perfectly, only this one using "#include <avr/wdt.h> » don’t want to compile
Take care.
Best regards.
Frederic.

**Comment by arkhipenko** [comment]
Hi,
WeMos D1 R2 is ESP8266 based controller. ESP8266 is not an avr board, therefore avr/wdt.h is not defined for it.
ESP8266 has a watchdog timer, but it is different.
Sorry I cannot help you with this - have not worked with ESPs enough to know.

**Comment by Fbo06** [comment]
Hi Anatoli Thank you for your research, i will look for this watchdog.

**Comment by arkhipenko** [comment]
Here is a link that seems to address your question:

http://www.esp8266.com/viewtopic.php?f=32&t=2776

**Comment by arkhipenko** [comment]
Check this post. Seems relevant:
http://www.esp8266.com/viewtopic.php?f=32&t=2776

Date: Sat, 30 Jul 2016 23:49:31 -0700

**Comment by Fbo06** [comment]
Thank you, i also have a link https://github.com/esp8266/Arduino/issues/1532 and i try it it's work but i don't know how to save the status of pin to restore them after re booting.

**Comment by arkhipenko** [comment]
Could you describe what you are trying to achieve?




Sent from a mobile device. Apologies for accidental typos.






On Sun, Jul 31, 2016 at 1:26 PM -0400, "Fbo06" <notifications@github.com> wrote:





Thank you, i also have a link https://github.com/esp8266/Arduino/issues/1532 and i try it it's work but i don't know how to save the status of pin to restore them after re booting.

---
