### ISSUE TITLE
Real Time

### ISSUE THREAD

**Issue by lv2eof** [arkhipenko/TaskScheduler#20]
Hi Anatoli,
How are you?
Well, just another simple question.
Can your library be considered of Real Time?
Thanks,
Luis

**Comment by arkhipenko** [comment]
Hi Luis,
If you have questions, instead of creating issues you can email me directly: arkhipenko@hotmail.com

To answer your question:
No, TaskScheduler can not be considered a real time scheduler.
By design, TaskScheduler implements cooperative multitasking, which is not pre-emptive. 
TaskScheduled can not guarantee execution of a Task on time in case previous Task is running long.
TaskScheduler will try to "catch up" to the schedule in case a misbehaving Task delayed everyone else, but it cannot stop a long-running task and switch to another. 
There is a way to prioritize Tasks, so more critical ones are evaluated for execution more often, but still, one long running task can basically block the whole chain. 

There are pros and cons of cooperative multitasking, but it is not real time. 
TaskScheduler has methods which allow you to detect long-running tasks, but not prevent them. 
I discuss this in the documentation, which I encourage you to review:
http://www.smart4smart.com/TaskScheduler.html
or a word doc included in the github package.

Hope this helps.
