### ISSUE TITLE
how long from enable.

### ISSUE THREAD

**Issue by tarzan115** [arkhipenko/TaskScheduler#50]
Hi @arkhipenko, I think the library should have a method to calculate time in the millisecond, minutes... from enable a Task.

**Comment by arkhipenko** [comment]
Good idea. Let me think about it.
________________________________

**Comment by arkhipenko** [comment]
Upon thinking more about it I think this is a very specific case that could be covered by storing task-related information using Local Task Storage (#define _TASK_LTS_POINTER compilation directive). 
The reason is: it is additional 4 bytes per Task that will be there permanently there while this use case seems to be a one-off (never been requested before).
