### ISSUE TITLE
issue with MightyCore

### ISSUE THREAD

**Issue by CRI73** [arkhipenko/TaskScheduler#57]
Hi
I have problem with Optiboot -- https://github.com/MCUdude/MightyCore -- ATmega644P 

In file included from /Users/omegapro/Documents/Arduino/libraries/libraries/LCDMenuLib2/src/LCDMenuLib2.h:142:0,
                 from /Users/omegapro/Google Drive/Elettronica/ASKO/Software/prova menu/LCDML_031_i2c_display_20x4/LCDML_031_i2c_display_20x4.ino:6:
/Users/omegapro/Documents/Arduino/libraries/libraries/LCDMenuLib2/src/LCDMenuLib2_macros.h:101:88: error: invalid conversion from 'void (*)()' to 'LCDML_FuncPtr_pu8 {aka void (*)(unsigned char)}' [-fpermissive]
         LCDMenuLib2_menu parent ## _ ## child(id, param, settings, callback, condition ); \
                                                                                                                                           ^

                                                                                       ^
/Users/omegapro/Documents/Arduino/libraries/libraries/LCDMenuLib2/src/LCDMenuLib2_macros.h:107:9: note: in expansion of macro 'LCDML_addAdvanced'
         LCDML_addAdvanced(id, parent, child, NULL, content, callback, 0, _LCDML_TYPE_default)
         ^
/Users/omegapro/Google Drive/Elettronica/ASKO/Software/prova menu/LCDML_031_i2c_display_20x4/LCDML_031_i2c_display_20x4.ino:77:3: note: in expansion of macro 'LCDML_add'
   LCDML_add         (8  , LCDML_0_1     , 5  , "Imp. Caldaia"     , temp_caldaia);
   ^
In file included from /Users/omegapro/Documents/Arduino/libraries/libraries/LCDMenuLib2/src/LCDMenuLib2.h:121:0,
                 from /Users/omegapro/Google Drive/Elettronica/ASKO/Software/prova menu/LCDML_031_i2c_display_20x4/LCDML_031_i2c_display_20x4.ino:6:
/Users/omegapro/Documents/Arduino/libraries/libraries/LCDMenuLib2/src/LCDMenuLib2_menu.h:73:13: error:   initializing argument 4 of 'LCDMenuLib2_menu::LCDMenuLib2_menu(uint8_t, uint8_t, uint8_t, LCDML_FuncPtr_pu8, LCDML_FuncPtr_rb)' [-fpermissive]
             LCDMenuLib2_menu(uint8_t p_id, uint8_t p_param, uint8_t p_configuration, LCDML_FuncPtr_pu8 p_callback_function, LCDML_FuncPtr_rb p_condition_function);
^

THANKS in advance for your help !!!!
Cristian

**Comment by arkhipenko** [comment]
Not sure what the issue was, but it seems you figured it out!

Sent from a mobile device. Apologies for accidental typos.

On Jul 12, 2018 10:50 AM, CRI73 <notifications@github.com> wrote:

Hi
I have problem with Optiboot -- https://github.com/MCUdude/MightyCore -- ATmega644P

In file included from /Users/omegapro/Documents/Arduino/libraries/libraries/LCDMenuLib2/src/LCDMenuLib2.h:142:0,
from /Users/omegapro/Google Drive/Elettronica/ASKO/Software/prova menu/LCDML_031_i2c_display_20x4/LCDML_031_i2c_display_20x4.ino:6:
/Users/omegapro/Documents/Arduino/libraries/libraries/LCDMenuLib2/src/LCDMenuLib2_macros.h:101:88: error: invalid conversion from 'void ()()' to 'LCDML_FuncPtr_pu8 {aka void ()(unsigned char)}' [-fpermissive]
LCDMenuLib2_menu parent ## _ ## child(id, param, settings, callback, condition );
^

                                                                                   ^


/Users/omegapro/Documents/Arduino/libraries/libraries/LCDMenuLib2/src/LCDMenuLib2_macros.h:107:9: note: in expansion of macro 'LCDML_addAdvanced'
LCDML_addAdvanced(id, parent, child, NULL, content, callback, 0, _LCDML_TYPE_default)
^
/Users/omegapro/Google Drive/Elettronica/ASKO/Software/prova menu/LCDML_031_i2c_display_20x4/LCDML_031_i2c_display_20x4.ino:77:3: note: in expansion of macro 'LCDML_add'
LCDML_add (8 , LCDML_0_1 , 5 , "Imp. Caldaia" , temp_caldaia);
^
In file included from /Users/omegapro/Documents/Arduino/libraries/libraries/LCDMenuLib2/src/LCDMenuLib2.h:121:0,
from /Users/omegapro/Google Drive/Elettronica/ASKO/Software/prova menu/LCDML_031_i2c_display_20x4/LCDML_031_i2c_display_20x4.ino:6:
/Users/omegapro/Documents/Arduino/libraries/libraries/LCDMenuLib2/src/LCDMenuLib2_menu.h:73:13: error: initializing argument 4 of 'LCDMenuLib2_menu::LCDMenuLib2_menu(uint8_t, uint8_t, uint8_t, LCDML_FuncPtr_pu8, LCDML_FuncPtr_rb)' [-fpermissive]
LCDMenuLib2_menu(uint8_t p_id, uint8_t p_param, uint8_t p_configuration, LCDML_FuncPtr_pu8 p_callback_function, LCDML_FuncPtr_rb p_condition_function);
^

THANKS in advance for your help !!!!
Cristian
